export const FETCH_CHARACTERS = 'CHARACTERS/FETCH_CHARACTERS';
export const SET_INFORMATION_CHARACTERS = 'CHARACTERS/SET_INFORMATION';

export const FETCH_EPISODES = 'EPISODES/FETCH_EPISODES';
export const SET_INFORMATION_EPISODES = 'EPISODES/SET_INFORMATION';

export const FETCH_LOCATIONS = 'LOCATIONS/FETCH_LOCATIONS';
export const SET_INFORMATION_LOCATIONS = 'LOCATIONS/SET_INFORMATION';

export const SET_LOADING = 'APP/SET_LOADING';
export const SET_MODAL_SHOW = 'APP/SET_MODAL_SHOW';
export const SET_MODAL_DATA = 'APP/SET_MODAL_DATA';
export const SET_FILTER_TYPES = 'APP/SET_FILTER_TYPES';
export const SET_FILTER_INPUT = 'APP/SET_FILTER_INPUT';
export const SET_SHOW_ALERT = 'APP/SET_SHOW_ALERT';
